apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sync
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sync
    spec:
      containers:
        - name: sync
          image: "ghcr.io/katexochen/sync:v0.0.0"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sync
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: sync
  type: LoadBalancer
