apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sync
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sync
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sync
    spec:
      containers:
        - name: sync
          image: "ghcr.io/katexochen/sync:v0.0.2"
          ports:
            - containerPort: 8080
          env:
            - name: FIFO_DB_PATH
              value: "/state/fifo.db"
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
          volumeMounts:
            - name: fifo-db
              mountPath: /state
  volumeClaimTemplates:
    - metadata:
        name: fifo-db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sync
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: sync
  type: LoadBalancer
